config/routes.rb
Rails.application.routes.draw do
  # Pages
  root 'pages#home'
  # Carts
  get '/cart', to: 'carts#show', as: 'cart'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  namespace :admin do
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'
    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'
    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'    
    get 'statuses',             to: 'statuses#index',   as: 'statuses'
    get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'
    post    'statuses',            to: 'statuses#create'
    put     'statuses/:id',        to: 'statuses#update'
    patch   'statuses/:id',        to: 'statuses#update'
    delete  'statuses/:id',        to: 'statuses#destroy'    
    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'
    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users

    validates :name, presence: true, uniqueness: true
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController

  layout 'admin_layout'
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  # GET /roles
  def index
    @roles = Role.all
  end

  # GET /roles/:id
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/:id/edit
  def edit
  end

  # POST /roles
  def create
    @role = Role.new(params_role)
    if @role.save
      redirect_to admin_roles_path
    else
      render :new
    end
  end

  # PUT/PATCH /roles/:id
  def update
    if @role.update(params_role)
      redirect_to admin_roles_path
    else
      render :edit
    end
  end

  # DELETE /roles/:id
  def destroy
    @role.destroy
    redirect_to admin_roles_path
  end
  
  private
  def set_role
    @role = Role.find(params[:id])
  rescue
    flash[:set_role_error] = "Could not find the record #{params[:id]}"
    redirect_to admin_roles_path
  end

  def params_role
    params.require(:role).permit(:name)
  end
end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/views/admin/roles/_form.html.erb
<!-- VARIABLES: base_role -->
<div class="card">
    <div class="card-body">
        <%= form_with(model: [:admin, base_role]) do |form| %>
            <div class="mb-3">
                <%= form.label :name, class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control' %>
                <% if base_role.errors[:name].any? %>
                    <div>
                        <%= base_role.errors[:name].first %>
                    </div>
                <% end %>
            </div>

            <%= form.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/admin/roles/edit.html.erb
<h1>Edit role</h1>

<%= render "form", base_role: @role %>

app/views/admin/roles/index.html.erb
<h3>Roles</h3>

<div class="card">
    <div class="card-body">
        <h5> Index </h5>
        <%= link_to "New", admin_new_role_path, class: 'btn btn-primary' %>

        <% if flash[:set_role_error] %>
          <%= flash[:set_role_error] %>
        <% end %>

        <table class="table table-hover">
            <tr>
                <th> Name   </th>
                <th> Action </th>
            </tr>
            <% @roles.each do |r| %>
                <tr>
                    <td> <%= r.name %></td>
                    <td>
                        <%= link_to "Edit", admin_edit_role_path(r), class: 'btn btn-warning' %>
                        <%= link_to "Delete", admin_role_path(r), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/admin/roles/new.html.erb
<h1>New Role</h1>

<%= render "form", base_role: @role %>

app/views/admin/roles/show.html.erb
<h1>Admin::Roles#show</h1>
<p>Find me in app/views/admin/roles/show.html.erb</p>